name: Build Check
on:
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Format
        run: yarn format

      - name: Build
        run: |
          yarn build
          touch ./dist/.nojekyll
