name: Build Check
on:
  workflow_run:
    workflows: ["Prettier"]
    types:
      - completed

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build
          touch ./dist/.nojekyll
